from typing import Protocol

from mathwizard.models.domain.figure import Figure, FigureDraft


class FigureRepository(Protocol):
    def add(self, draft: FigureDraft) -> Figure: ...

    def get(self, figure_id: int) -> Figure: ...

    def get_by_slug(self, slug: str) -> Figure | None: ...

    def upsert(self, draft: FigureDraft) -> Figure: ...

    def list(self) -> list[Figure]: ...
