from typing import Protocol

from mathwizard.models.domain.roster import Student, Teacher


class RosterRepository(Protocol):
    def add_teacher(self, user_id: int) -> Teacher: ...

    def add_student(self, user_id: int, teacher_id: int) -> Student: ...

    def get_teacher(self, teacher_id: int) -> Teacher | None: ...

    def get_teacher_by_user_id(self, user_id: int) -> Teacher | None: ...

    def get_student_by_user_id(self, user_id: int) -> Student | None: ...

    def list_students_for_teacher(self, teacher_id: int) -> list[Student]: ...
