from __future__ import annotations

from pydantic import BaseModel, ConfigDict, model_validator  # type: ignore


class MultipartQuestionPart(BaseModel):
    """A single part of a multipart question."""

    text: str
    label: str | None = None  # Auto-generated (a, b, c) if None
    points: int = 0

    model_config = ConfigDict(extra="forbid")


class AgentMultipartQuestionOutput(BaseModel):
    """
    Agent output for multipart question formatting.

    This is what the LLM agent returns - ONLY the formatted text content.
    The agent's job is to parse question text into structured parts (title, stem, parts).

    Metadata like exam_id, calculator_allowed, and image paths are NOT generated
    by the agent - they are added afterward from QuestionRecord.

    Use MultipartQuestionOutput (which extends this) for the full model with metadata.
    """

    title: str
    stem: str
    parts: list[MultipartQuestionPart]

    model_config = ConfigDict(extra="forbid")

    @model_validator(mode="after")
    def auto_generate_part_labels(self) -> "AgentMultipartQuestionOutput":
        """Auto-generate labels (a, b, c) for parts without explicit labels."""
        for i, part in enumerate(self.parts):
            if part.label is None:
                part.label = chr(ord("a") + i)
        return self


class MultipartQuestionOutput(AgentMultipartQuestionOutput):
    """
    Complete multipart question model with metadata.

    This extends AgentMultipartQuestionOutput by adding metadata fields that are
    NOT generated by the LLM agent:
    - exam_id, calculator_allowed: Question metadata
    - page_images, figure_images: Forwarded from QuestionRecord

    Used for:
    - Storing formatted questions (YAML files)
    - Practice exercises
    - Vectorstore operations
    - Web display
    """

    # Optional metadata (not generated by agent)
    exam_id: str | None = None
    calculator_allowed: bool | None = None

    # Image paths (forwarded from QuestionRecord, not agent-generated)
    page_images: list[str] = []
    figure_images: list[str] = []

    model_config = ConfigDict(extra="forbid")

    @property
    def max_marks(self) -> int:
        """Computed property: sum of all part points."""
        return sum(part.points for part in self.parts)

